name: CI

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'
    - run: npm install
    - run: make test
    - run: make lint
    - run: make build
    - run: make pack
    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: runbookmd
        path: '*.vsix' 